// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file yeying/api/correction/homework.proto (package yeying.api.correction, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, MessageHeaderJson, ResponseStatus, ResponseStatusJson } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { HomeworkMetadata, HomeworkMetadataJson } from "./meta_pb";
import { file_yeying_api_correction_meta } from "./meta_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/correction/homework.proto.
 */
export const file_yeying_api_correction_homework: GenFile = /*@__PURE__*/
  fileDesc("CiR5ZXlpbmcvYXBpL2NvcnJlY3Rpb24vaG9tZXdvcmsucHJvdG8SFXlleWluZy5hcGkuY29ycmVjdGlvbiKFAQoTSG9tZXdvcmtMaXN0UmVxdWVzdBIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEjwKBGJvZHkYAiABKAsyLi55ZXlpbmcuYXBpLmNvcnJlY3Rpb24uSG9tZXdvcmtMaXN0UmVxdWVzdEJvZHkiJgoXSG9tZXdvcmtMaXN0UmVxdWVzdEJvZHkSCwoDZGlkGAEgASgJIocBChRIb21ld29ya0xpc3RSZXNwb25zZRIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEj0KBGJvZHkYAiABKAsyLy55ZXlpbmcuYXBpLmNvcnJlY3Rpb24uSG9tZXdvcmtMaXN0UmVzcG9uc2VCb2R5IoQBChhIb21ld29ya0xpc3RSZXNwb25zZUJvZHkSMQoGc3RhdHVzGAEgASgLMiEueWV5aW5nLmFwaS5jb21tb24uUmVzcG9uc2VTdGF0dXMSNQoEbGlzdBgCIAMoCzInLnlleWluZy5hcGkuY29ycmVjdGlvbi5Ib21ld29ya01ldGFkYXRhIokBChVIb21ld29ya0RldGFpbFJlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI+CgRib2R5GAIgASgLMjAueWV5aW5nLmFwaS5jb3JyZWN0aW9uLkhvbWV3b3JrRGV0YWlsUmVxdWVzdEJvZHkiKAoZSG9tZXdvcmtEZXRhaWxSZXF1ZXN0Qm9keRILCgN1aWQYASABKAkiiwEKFkhvbWV3b3JrRGV0YWlsUmVzcG9uc2USMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI/CgRib2R5GAIgASgLMjEueWV5aW5nLmFwaS5jb3JyZWN0aW9uLkhvbWV3b3JrRGV0YWlsUmVzcG9uc2VCb2R5IoYBChpIb21ld29ya0RldGFpbFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxI1CgRtZXRhGAIgASgLMicueWV5aW5nLmFwaS5jb3JyZWN0aW9uLkhvbWV3b3JrTWV0YWRhdGEy1gEKCEhvbWV3b3JrEmEKBExpc3QSKi55ZXlpbmcuYXBpLmNvcnJlY3Rpb24uSG9tZXdvcmtMaXN0UmVxdWVzdBorLnlleWluZy5hcGkuY29ycmVjdGlvbi5Ib21ld29ya0xpc3RSZXNwb25zZSIAEmcKBkRldGFpbBIsLnlleWluZy5hcGkuY29ycmVjdGlvbi5Ib21ld29ya0RldGFpbFJlcXVlc3QaLS55ZXlpbmcuYXBpLmNvcnJlY3Rpb24uSG9tZXdvcmtEZXRhaWxSZXNwb25zZSIAQhdaFXlleWluZy9hcGkvY29ycmVjdGlvbmIGcHJvdG8z", [file_yeying_api_common_message, file_yeying_api_correction_meta]);

/**
 * 列表
 *
 * @generated from message yeying.api.correction.HomeworkListRequest
 */
export type HomeworkListRequest = Message<"yeying.api.correction.HomeworkListRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.correction.HomeworkListRequestBody body = 2;
   */
  body?: HomeworkListRequestBody;
};

/**
 * 列表
 *
 * @generated from message yeying.api.correction.HomeworkListRequest
 */
export type HomeworkListRequestJson = {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeaderJson;

  /**
   * @generated from field: yeying.api.correction.HomeworkListRequestBody body = 2;
   */
  body?: HomeworkListRequestBodyJson;
};

/**
 * Describes the message yeying.api.correction.HomeworkListRequest.
 * Use `create(HomeworkListRequestSchema)` to create a new message.
 */
export const HomeworkListRequestSchema: GenMessage<HomeworkListRequest, HomeworkListRequestJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 0);

/**
 * @generated from message yeying.api.correction.HomeworkListRequestBody
 */
export type HomeworkListRequestBody = Message<"yeying.api.correction.HomeworkListRequestBody"> & {
  /**
   * 学生ID
   *
   * @generated from field: string did = 1;
   */
  did: string;
};

/**
 * @generated from message yeying.api.correction.HomeworkListRequestBody
 */
export type HomeworkListRequestBodyJson = {
  /**
   * 学生ID
   *
   * @generated from field: string did = 1;
   */
  did?: string;
};

/**
 * Describes the message yeying.api.correction.HomeworkListRequestBody.
 * Use `create(HomeworkListRequestBodySchema)` to create a new message.
 */
export const HomeworkListRequestBodySchema: GenMessage<HomeworkListRequestBody, HomeworkListRequestBodyJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 1);

/**
 * @generated from message yeying.api.correction.HomeworkListResponse
 */
export type HomeworkListResponse = Message<"yeying.api.correction.HomeworkListResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.correction.HomeworkListResponseBody body = 2;
   */
  body?: HomeworkListResponseBody;
};

/**
 * @generated from message yeying.api.correction.HomeworkListResponse
 */
export type HomeworkListResponseJson = {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeaderJson;

  /**
   * @generated from field: yeying.api.correction.HomeworkListResponseBody body = 2;
   */
  body?: HomeworkListResponseBodyJson;
};

/**
 * Describes the message yeying.api.correction.HomeworkListResponse.
 * Use `create(HomeworkListResponseSchema)` to create a new message.
 */
export const HomeworkListResponseSchema: GenMessage<HomeworkListResponse, HomeworkListResponseJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 2);

/**
 * @generated from message yeying.api.correction.HomeworkListResponseBody
 */
export type HomeworkListResponseBody = Message<"yeying.api.correction.HomeworkListResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * repeated 表示 List
   *
   * @generated from field: repeated yeying.api.correction.HomeworkMetadata list = 2;
   */
  list: HomeworkMetadata[];
};

/**
 * @generated from message yeying.api.correction.HomeworkListResponseBody
 */
export type HomeworkListResponseBodyJson = {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatusJson;

  /**
   * repeated 表示 List
   *
   * @generated from field: repeated yeying.api.correction.HomeworkMetadata list = 2;
   */
  list?: HomeworkMetadataJson[];
};

/**
 * Describes the message yeying.api.correction.HomeworkListResponseBody.
 * Use `create(HomeworkListResponseBodySchema)` to create a new message.
 */
export const HomeworkListResponseBodySchema: GenMessage<HomeworkListResponseBody, HomeworkListResponseBodyJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 3);

/**
 * 详情
 *
 * @generated from message yeying.api.correction.HomeworkDetailRequest
 */
export type HomeworkDetailRequest = Message<"yeying.api.correction.HomeworkDetailRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.correction.HomeworkDetailRequestBody body = 2;
   */
  body?: HomeworkDetailRequestBody;
};

/**
 * 详情
 *
 * @generated from message yeying.api.correction.HomeworkDetailRequest
 */
export type HomeworkDetailRequestJson = {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeaderJson;

  /**
   * @generated from field: yeying.api.correction.HomeworkDetailRequestBody body = 2;
   */
  body?: HomeworkDetailRequestBodyJson;
};

/**
 * Describes the message yeying.api.correction.HomeworkDetailRequest.
 * Use `create(HomeworkDetailRequestSchema)` to create a new message.
 */
export const HomeworkDetailRequestSchema: GenMessage<HomeworkDetailRequest, HomeworkDetailRequestJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 4);

/**
 * @generated from message yeying.api.correction.HomeworkDetailRequestBody
 */
export type HomeworkDetailRequestBody = Message<"yeying.api.correction.HomeworkDetailRequestBody"> & {
  /**
   * @generated from field: string uid = 1;
   */
  uid: string;
};

/**
 * @generated from message yeying.api.correction.HomeworkDetailRequestBody
 */
export type HomeworkDetailRequestBodyJson = {
  /**
   * @generated from field: string uid = 1;
   */
  uid?: string;
};

/**
 * Describes the message yeying.api.correction.HomeworkDetailRequestBody.
 * Use `create(HomeworkDetailRequestBodySchema)` to create a new message.
 */
export const HomeworkDetailRequestBodySchema: GenMessage<HomeworkDetailRequestBody, HomeworkDetailRequestBodyJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 5);

/**
 * @generated from message yeying.api.correction.HomeworkDetailResponse
 */
export type HomeworkDetailResponse = Message<"yeying.api.correction.HomeworkDetailResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.correction.HomeworkDetailResponseBody body = 2;
   */
  body?: HomeworkDetailResponseBody;
};

/**
 * @generated from message yeying.api.correction.HomeworkDetailResponse
 */
export type HomeworkDetailResponseJson = {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeaderJson;

  /**
   * @generated from field: yeying.api.correction.HomeworkDetailResponseBody body = 2;
   */
  body?: HomeworkDetailResponseBodyJson;
};

/**
 * Describes the message yeying.api.correction.HomeworkDetailResponse.
 * Use `create(HomeworkDetailResponseSchema)` to create a new message.
 */
export const HomeworkDetailResponseSchema: GenMessage<HomeworkDetailResponse, HomeworkDetailResponseJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 6);

/**
 * @generated from message yeying.api.correction.HomeworkDetailResponseBody
 */
export type HomeworkDetailResponseBody = Message<"yeying.api.correction.HomeworkDetailResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: yeying.api.correction.HomeworkMetadata meta = 2;
   */
  meta?: HomeworkMetadata;
};

/**
 * @generated from message yeying.api.correction.HomeworkDetailResponseBody
 */
export type HomeworkDetailResponseBodyJson = {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatusJson;

  /**
   * @generated from field: yeying.api.correction.HomeworkMetadata meta = 2;
   */
  meta?: HomeworkMetadataJson;
};

/**
 * Describes the message yeying.api.correction.HomeworkDetailResponseBody.
 * Use `create(HomeworkDetailResponseBodySchema)` to create a new message.
 */
export const HomeworkDetailResponseBodySchema: GenMessage<HomeworkDetailResponseBody, HomeworkDetailResponseBodyJson> = /*@__PURE__*/
  messageDesc(file_yeying_api_correction_homework, 7);

/**
 * *
 * 作业管理
 * 对应 DB 表： correction.school_assignment
 *
 * @generated from service yeying.api.correction.Homework
 */
export const Homework: GenService<{
  /**
   * 列表
   *
   * @generated from rpc yeying.api.correction.Homework.List
   */
  list: {
    methodKind: "unary";
    input: typeof HomeworkListRequestSchema;
    output: typeof HomeworkListResponseSchema;
  },
  /**
   * 详情
   *
   * @generated from rpc yeying.api.correction.Homework.Detail
   */
  detail: {
    methodKind: "unary";
    input: typeof HomeworkDetailRequestSchema;
    output: typeof HomeworkDetailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_correction_homework, 0);

