// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file yeying/api/correction/imagecontent.proto (package yeying.api.correction, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file yeying/api/correction/imagecontent.proto.
 */
export const file_yeying_api_correction_imagecontent: GenFile = /*@__PURE__*/
  fileDesc("Cih5ZXlpbmcvYXBpL2NvcnJlY3Rpb24vaW1hZ2Vjb250ZW50LnByb3RvEhV5ZXlpbmcuYXBpLmNvcnJlY3Rpb24qOAoUSW1hZ2VDb250ZW50VHlwZUVudW0SDAoIUVVFU1RJT04QABIKCgZBTlNXRVIQARIGCgJRQRACKoABCg5UYXNrU3RhdHVzRW51bRILCgdDUkVBVEVEEAASEAoMV0FJVF9NQVJLSU5HEAESCwoHTUFSS0lORxACEhIKDkZJTklTSF9NQVJLSU5HEAMSDwoLV0FJVF9SRVZJU0UQBBIKCgZSRVZJU0UQBRIRCg1GSU5JU0hfUkVWSVNFEAZCF1oVeWV5aW5nL2FwaS9jb3JyZWN0aW9uYgZwcm90bzM");

/**
 * *
 * 图片内容类型
 *
 * @generated from enum yeying.api.correction.ImageContentTypeEnum
 */
export enum ImageContentTypeEnum {
  /**
   * *
   * 题目
   *
   * @generated from enum value: QUESTION = 0;
   */
  QUESTION = 0,

  /**
   * *
   * 答案
   *
   * @generated from enum value: ANSWER = 1;
   */
  ANSWER = 1,

  /**
   * *
   * 题目和答案
   *
   * @generated from enum value: QA = 2;
   */
  QA = 2,
}

/**
 * *
 * 图片内容类型
 *
 * @generated from enum yeying.api.correction.ImageContentTypeEnum
 */
export type ImageContentTypeEnumJson = "QUESTION" | "ANSWER" | "QA";

/**
 * Describes the enum yeying.api.correction.ImageContentTypeEnum.
 */
export const ImageContentTypeEnumSchema: GenEnum<ImageContentTypeEnum, ImageContentTypeEnumJson> = /*@__PURE__*/
  enumDesc(file_yeying_api_correction_imagecontent, 0);

/**
 * @generated from enum yeying.api.correction.TaskStatusEnum
 */
export enum TaskStatusEnum {
  /**
   * 创建、待批改（创建后用户还没有批改作业）、批改中（用户批改一部分作业）、批改完成、待订正、订正中、订正完成
   * 创建
   *
   * @generated from enum value: CREATED = 0;
   */
  CREATED = 0,

  /**
   * 待批改
   *
   * @generated from enum value: WAIT_MARKING = 1;
   */
  WAIT_MARKING = 1,

  /**
   * 批改中
   *
   * @generated from enum value: MARKING = 2;
   */
  MARKING = 2,

  /**
   * 批改完成
   *
   * @generated from enum value: FINISH_MARKING = 3;
   */
  FINISH_MARKING = 3,

  /**
   * 待订正
   *
   * @generated from enum value: WAIT_REVISE = 4;
   */
  WAIT_REVISE = 4,

  /**
   * 订正中
   *
   * @generated from enum value: REVISE = 5;
   */
  REVISE = 5,

  /**
   * 订正完成
   *
   * @generated from enum value: FINISH_REVISE = 6;
   */
  FINISH_REVISE = 6,
}

/**
 * @generated from enum yeying.api.correction.TaskStatusEnum
 */
export type TaskStatusEnumJson = "CREATED" | "WAIT_MARKING" | "MARKING" | "FINISH_MARKING" | "WAIT_REVISE" | "REVISE" | "FINISH_REVISE";

/**
 * Describes the enum yeying.api.correction.TaskStatusEnum.
 */
export const TaskStatusEnumSchema: GenEnum<TaskStatusEnum, TaskStatusEnumJson> = /*@__PURE__*/
  enumDesc(file_yeying_api_correction_imagecontent, 1);

